[package]
name = "ws2812-nop-samd21"
version = "0.1.0"
authors = ["Paul Sajna <sajattack@gmail.com>"]
edition = "2018"

[dependencies]
smart-leds-trait = {git = "https://github.com/smart-leds-rs/smart-leds-trait"}

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.1"

[dev-dependencies]
atsamd21-hal = "0.2"
circuit_playground_express = { git = "https://github.com/atsamd-rs/atsamd" }
cortex-m-rt = "0.5"
cortex-m = "0.5"
panic-halt = "0.2"
smart-leds = {git = "https://github.com/smart-leds-rs/smart-leds"}


[features]
# ask the HAL to enable atsamd21g18a support
default = ["rt", "atsamd21-hal/samd21g18a"]
rt = ["atsamd21-hal/samd21g18a-rt"]
unproven = ["atsamd21-hal/unproven"]
use_semihosting = []


